### ISSUE TITLE
any license restrictions for the collection?

### ISSUE THREAD

**Issue by zerwes** [evrardjp/ansible-collection-ha#2]
To be concrete:
repo/branch: https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy/tree/rls
plan: https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy/issues/6
But the original repo uses MIT license. Any objections?

**Comment by evrardjp** [comment]
None for me.

**Comment by zerwes** [comment]
for me neither :+1: #3
