### ISSUE TITLE
Adding protection rules?

### ISSUE THREAD

**Issue by evrardjp** [evrardjp/ansible-collection-ha#5]
Should we do things like:
- Require testing to pass before merging?
- Forcing to go through mrs?
- Protect branch main?
What's your opinion @zerwes  ?

**Comment by zerwes** [comment]
> Should we do things like:
> 
> * Require testing to pass before merging?

:+1: all tests should pass and a review should be mandatory too

> * Forcing to go through mrs?

Sorry, can you please be so kind and explain to me what you mean by this?

> * Protect branch main?

:+1: changes should come via PRs

**Comment by evrardjp** [comment]
Sorry, I used much gitlab recently, I meant forcing to go through PRs, instead of allowing a direct push to the branch. This is what you answered just before. :) 

Sounds cool, let me add this.

**Comment by evrardjp** [comment]
Done let's reopen a new issue if that does not work.

**Comment by zerwes** [comment]
> Require testing to pass before merging?

well ... I have to admit the haproxy CI is not yet up and running (it is still the old one from the original repo)

I will try to add some molecule testing as soon as I find the time Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy#9
And some ansibe-lint check too
As soon as I have them working, I can try to design some collection test running both roles in one play
